language: python

python:
  - "2.6"
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"
install: "pip install -r testing-requirements.txt"

#command to run tests
script: "nosetests"
